- name: introducting task level vars
  hosts: local
  connection: local
  vars:
    COURSE: "DevOps with AWS"
    DURATION: "150 HRS"
    TRAINER: "Shiva Reddy"
  Tasks:
  - name: This is task 1 with task level vars
    COURSE: "DevOps with Ansible"
    DURATION: "10 HRS"
    TRAINER: "Shashank Reddy"
    ansible.builtin.debug:
      msg: "The course is {{ COURSE }}, Duration is {{ DURATION }} and trainer is {{ TRAINER }}"
  - name: This is task 2 with play level vars
    ansible.builtin.debug:
      msg: "The course is {{ COURSE }}, Duration is {{ DURATION }} and trainer is {{ TRAINER }}"