- name: different filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: " {{ name | default('vijay') }}"
  - name: string to list convertion
    vars:
      fruits: "banana, apple, strawberry, carrot"
    ansible.builtin.debug:
      msg: " different fruits are {{ fruits | split(',') }}"
  - name: convert map to list
    vars:
      course:
        name: AWS
        duration: 10hrs
        trainer: VJ
    ansible.builtin.debug:
      msg: " course details are {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course: [ {'key': 'name', 'value': 'AWS'}, {'key': 'duration', 'value': '10hrs'},{'key': 'trainer', 'value': 'VJ'} ]
    ansible.builtin.debug:
      msg: "The course details are {{ course | items2map }}"