- name: different filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: " {{ name | default('vijay') }}"
  - name: string to list convertion
    vars:
      fruits: "banana, apple, strawberry, carrot"
    ansible.builtin.debug:
      msg: " different fruits are {{ fruits | split(',') }}"