- name: different filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: " {{ name | default('vijay') }}"
  - name: string to list convertion
    vars:
      fruits: "banana, apple, strawberry, carrot"
    ansible.builtin.debug:
      msg: " different fruits are {{ fruits | split(',') }}"
  - name: convert map to list
    vars:
      course:
        name: AWS
        duration: 10hrs
        trainer: VJ
    ansible.builtin.debug:
      msg: " course details are {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course: [ {'key': 'name', 'value': 'AWS'}, {'key': 'duration', 'value': '10hrs'},{'key': 'trainer', 'value': 'VJ'} ]
    ansible.builtin.debug:
      msg: "The course details are {{ course | items2dict }}"

  - name: everything upper
    vars:
      name: "viJay JOhN"
    ansible.builtin.debug:
      msg: " {{ name | upper }}"

  - name: everything lower
    vars:
      name: "viJay JOhN"
    ansible.builtin.debug:
      msg: " {{ name | lower }}"

  - name: print max and min number in a list
    vars:
      numbers: [1,23,455,8789,98902,0.5]
    ansible.builtin.debug:
      msg: "the min in list is {{ numbers | min}} and the max in the list is {{ numbers | max}}"